# Generated by Django 5.2.12 on 2026-03-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('daily_generation_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='song_gen.registereduser')),
            ],
            options={
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='GeneratedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('song_genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('HIP_HOP', 'Hip Hop'), ('CLASSICAL', 'Classical'), ('COUNTRY', 'Country'), ('RNB', 'R&B')], max_length=20)),
                ('singer_choice', models.CharField(choices=[('BOY', 'Boy'), ('GIRL', 'Girl')], max_length=10)),
                ('mood', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image_url', models.CharField(blank=True, max_length=2048)),
                ('duration', models.IntegerField()),
                ('share_url', models.CharField(blank=True, max_length=2048)),
                ('audio_url', models.CharField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song_gen.library')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_songs', to='song_gen.registereduser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
