# Generated by Django 5.2.5 on 2026-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsong',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TEXT_SUCCESS', 'Text Success'), ('FIRST_SUCCESS', 'First Success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedsong',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
